config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { registrations: :registrations, sessions: :sessions }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :results, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :badges, only: :index
  resources :own_badges, only: :index

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/own_badge.rb
class OwnBadge < ApplicationRecord
  belongs_to :user, inverse_of: :own_badges
  belongs_to :badge, inverse_of: :own_badges
end

app/controllers/own_badges_controller.rb
class OwnBadgesController < ApplicationController
  def index
    @own_badges = current_user.own_badges
  end
end

app/helpers/own_badges_helper.rb
module OwnBadgesHelper
end

app/views/own_badges/_own_badge.html.erb
<tr>
  <td class="align-middle d-flex align-items-center">
    <%= octicon 'smiley', class: 'text-success' %>
    <p class="pl-2"><%= own_badge.badge.title %></p>
  </td>
  <td class="align-middle"><%= own_badge.badge.description %></td>
</tr>

app/views/own_badges/index.html.erb
<% if @own_badges.present? %>

<h1>My badges list</h1>
<br/>
<table class="table">
  <th class="sort-by-title pointer">
    Title
    <%= octicon 'arrow-up', class: 'text-success hide' %>
    <%= octicon 'arrow-down', class: 'text-success hide' %>
  </th>
  <th>Description</th>
  <%= render @own_badges %>
</table>

<% else %>
  <p>You dont have any badges yet.</p>
  <%= link_to 'Click it to examine yourself!', tests_path %>
<% end %>

<%= link_to '<- Back', badges_path %>