config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { registrations: :registrations, sessions: :sessions }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :results, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :badges, only: :index
  resources :own_badges, only: :index

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/admin.rb
class Admin < User
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_answers_count, on: :create

  scope :correct, -> { where(correct: true) }

  attr_reader :answers

  def validate_answers_count
    errors.add(:answers, message: "can't be more the 4") if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :own_badges, inverse_of: :badge, dependent: :destroy

  validates :title, presence: true
  validates :rule, presence: true

  BADGE_TYPES = %w[all_category_tests_passed first_try_passed all_level_tests_passed].freeze
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests, dependent: :destroy

  validates :title, presence: true, uniqueness: true

  default_scope { order(title: :asc) }
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/own_badge.rb
class OwnBadge < ApplicationRecord
  belongs_to :user, inverse_of: :own_badges
  belongs_to :badge, inverse_of: :own_badges
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  belongs_to :test

  validates :body, presence: true
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user, inverse_of: :results
  belongs_to :test, inverse_of: :results
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :set_first_question, on: :create

  SUCCESS_TRESHOLD = 85

  scope :success_passed, -> { where('passage_percent >= ?', SUCCESS_TRESHOLD) }

  def completed?
    current_question.nil? || times_up?
  end

  def accept!(answer_ids)
    return if times_up?

    self.correct_answers += 1 if correct_answer?(answer_ids)
    self.current_question = set_next_question
    save!
  end

  def success_result?
    correct_answers_percent.to_i >= SUCCESS_TRESHOLD
  end

  def correct_answers_percent
    self.correct_answers.zero? ? 0 : (self.correct_answers.to_f / self.test.questions.each { |q| q.answers.correct }.count * 100).to_i
  end

  def current_question_number
    test.questions.order(:id).where('id < ?', current_question.id).size + 1
  end

  def calculate_passage_percent
    update!(passage_percent: correct_answers_percent)
  end

  def times_up?
    times_up <= Time.current
  end

  def left_time
    time = times_up - Time.current
    time.positive? ? time : 0
  end

  private

  def times_up
    created_at + test.minutes_for_passing.minutes
  end

  def set_first_question
    self.current_question = test.questions.first
  end

  def correct_answer?(answer_ids)
    test_correct_answers.ids.sort == answer_ids&.map(&:to_i)&.sort
  end

  def test_correct_answers
    current_question.answers.correct
  end

  def set_next_question
    test.questions.order(:id).find_by('id > ?', self.current_question.id)
  end
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User', inverse_of: :tests

  has_many :questions, dependent: :destroy
  has_many :results, inverse_of: :test, dependent: :destroy
  has_many :users, through: :results

  validates :title, presence: true
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, uniqueness: { scope: :title }
  validates :minutes_for_passing, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }
  scope :tests_by, ->(category) { joins(:category).where(categories: { title: category }).order(title: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :trackable,
         :rememberable,
         :validatable,
         :confirmable

  has_many :results, inverse_of: :user, dependent: :destroy
  has_many :tests, through: :results
  has_many :created_tests, class_name: 'Test', foreign_key: :author_id, inverse_of: :author, dependent: :destroy
  has_many :gists, dependent: :destroy
  has_many :own_badges, inverse_of: :user, dependent: :destroy
  has_many :badges, through: :own_badges

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :email, format: { with: /\A[a-z0-9+\-_.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: 'invalid format' }

  def results_list_by(level)
    Test.joins(:results)
        .where(results: { user_id: id }, level: level)
  end

  def test_passage(test)
    results.order(id: :desc).find_by(test_id: test.id)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = Badge.all
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_test_passage, only: %i[show update result gist]

  def show; end

  def result; end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      @test_passage.calculate_passage_percent
      give_badge
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_result_path(@test_passage)
    else
      render :show
    end
  end

  def gist
    result = GistQuestionService.new(@test_passage.current_question).call

    if result.success?
      Gist.create(url: result.html_url, user: current_user, question: @test_passage.current_question)
      flash[:notice] = t('gist.success', url: result.html_url)
    else
      flash[:alert] = t('gist.failure')
    end

    redirect_to @test_passage
  end

  private

  def set_test_passage
    @test_passage = Result.find(params[:id])
  end

  def give_badge
    badges = BadgeService.new(@test_passage).call

    return if badges.empty?

    current_user.badges << badges
    flash[:notice] = t('badges.earn_badge')
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :find_test, only: :start

  def index
    @tests = Test.all
  end

  def start
    if user_signed_in?
      current_user.tests.push(@test)
      redirect_to current_user.test_passage(@test)
    else
      redirect_to login_path
    end
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    link_to author.to_s, repo.to_s, target: '_blank', rel: 'noopener noreferrer'
  end

  def header_menu(current_user)
    if user_signed_in?
      render partial: 'shared/user', locals: { user: current_user }
    else
      link_to 'Log in', new_user_session_path
    end
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
  def badge_form_header(badge)
    if badge.persisted?
      "Edit #{badge.title}"
    else
      'Create New badge'
    end
  end
end

app/helpers/own_badges_helper.rb
module OwnBadgesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_form_header(question)
    if question.persisted?
      "Edit #{question.test.title} question"
    else
      "Create New #{question.test.title} question"
    end
  end
end

app/helpers/results_helper.rb
module ResultsHelper
  def questions_counter(test_passage)
    "Question #{test_passage.test.questions.find_index(test_passage.current_question) + 1}/#{test_passage.test.questions.count}"
  end
end

app/helpers/tests_helper.rb
module TestsHelper
  def test_form_header(test)
    if test.persisted?
      "Edit #{test.title}"
    else
      'Create New test'
    end
  end

  def convert_test_level(level)
    case level
    when 0..1 then 'Easy'
    when 2..4 then 'Medium'
    else
      'Hard'
    end
  end
end

app/views/admin/_nav.html.erb
<header class='header'>
  <p class='title admin'><%= link_to 'AdminPanel | TestGuru', admin_tests_path %></p>
  <p class='gists-nav'><%= link_to 'Gists', admin_gists_path %></p>
  <p class='admin-badges-nav'><%= link_to 'Badges', admin_badges_path %></p>
  <p class='menu'><%= header_menu(current_user) %>
  <% if user_signed_in? %>
  <span class='logout'>
    <%= link_to 'Log out',
              destroy_user_session_path,
              method: :delete %>
  </span>
  <% end %>
  </p>
</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Panel | TestGuru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'admin/nav', locals:{current_user: current_user}%>

    <div class='content'>
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestGuru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header', locals:{current_user: current_user}%>

    <div class='content'>
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div, class: 'error-message', data: {resource_id: resource.id} do %>
    <h2><%= pluralize(resource.errors.count, 'error') %> detected:<h2>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
   <% end %>
 <% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :p, message, class: "flash #{key}" %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <p><%= current_year %></p>
  <p><%= github_url 'Areukiddin github', 'https://github.com/Areukiddin' %></p>
  <p><%= link_to 'Учебный проект в онлайн-школе Thinknetica', 'http://thinknetica.com', target: '_blank' %></p>
 </footer>

app/views/shared/_header.html.erb
<header class='header'>
  <p class='title'><%= link_to 'TestGuru', root_path %></p>
  <p class="user-badges-nav"><%= link_to 'Badges', badges_path %></p>
  <p class='menu'><%= header_menu(current_user) %>
  <% if user_signed_in? %>
  <span class='logout'>
    <%= link_to 'Log out',
              destroy_user_session_path,
              method: :delete %>
  </span>
  <% end %>
  </p>
</header>

app/views/shared/_user.html.erb
<span>Welcome, <b><%= user.first_name %> <%= user.last_name %></b> Guru!</span>