config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { registrations: :registrations, sessions: :sessions }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :results, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :badges, only: :index
  resources :own_badges, only: :index

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  belongs_to :test

  validates :body, presence: true
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user, inverse_of: :results
  belongs_to :test, inverse_of: :results
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :set_first_question, on: :create

  SUCCESS_TRESHOLD = 85

  scope :success_passed, -> { where('passage_percent >= ?', SUCCESS_TRESHOLD) }

  def completed?
    current_question.nil? || times_up?
  end

  def accept!(answer_ids)
    return if times_up?

    self.correct_answers += 1 if correct_answer?(answer_ids)
    self.current_question = set_next_question
    save!
  end

  def success_result?
    correct_answers_percent.to_i >= SUCCESS_TRESHOLD
  end

  def correct_answers_percent
    self.correct_answers.zero? ? 0 : (self.correct_answers.to_f / self.test.questions.each { |q| q.answers.correct }.count * 100).to_i
  end

  def current_question_number
    test.questions.order(:id).where('id < ?', current_question.id).size + 1
  end

  def calculate_passage_percent
    update!(passage_percent: correct_answers_percent)
  end

  def times_up?
    times_up <= Time.current
  end

  def left_time
    time = times_up - Time.current
    time.positive? ? time : 0
  end

  private

  def times_up
    created_at + test.minutes_for_passing.minutes
  end

  def set_first_question
    self.current_question = test.questions.first
  end

  def correct_answer?(answer_ids)
    test_correct_answers.ids.sort == answer_ids&.map(&:to_i)&.sort
  end

  def test_correct_answers
    current_question.answers.correct
  end

  def set_next_question
    test.questions.order(:id).find_by('id > ?', self.current_question.id)
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_test_passage, only: %i[show update result gist]

  def show; end

  def result; end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      @test_passage.calculate_passage_percent
      give_badge
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_result_path(@test_passage)
    else
      render :show
    end
  end

  def gist
    result = GistQuestionService.new(@test_passage.current_question).call

    if result.success?
      Gist.create(url: result.html_url, user: current_user, question: @test_passage.current_question)
      flash[:notice] = t('gist.success', url: result.html_url)
    else
      flash[:alert] = t('gist.failure')
    end

    redirect_to @test_passage
  end

  private

  def set_test_passage
    @test_passage = Result.find(params[:id])
  end

  def give_badge
    badges = BadgeService.new(@test_passage).call

    return if badges.empty?

    current_user.badges << badges
    flash[:notice] = t('badges.earn_badge')
  end
end

app/helpers/results_helper.rb
module ResultsHelper
  def questions_counter(test_passage)
    "Question #{test_passage.test.questions.find_index(test_passage.current_question) + 1}/#{test_passage.test.questions.count}"
  end
end

app/views/results/_fail.html.erb
<h2 class="test-fail"><%= "Unfortunately, test failed with #{percent}% correct answers. Next time will be better!" %></h2>

app/views/results/_success.html.erb
<h2 class="test-success"><%= "You successfully pass the test with #{percent}% correct answers. Congratulations!" %></h2>

app/views/results/result.html.erb
<h1>The <%= @test_passage.test.title %> test was completed!</h1>
<br/>
<% if @test_passage.success_result? then %>
<%= render partial: 'success', locals: {percent: @test_passage.passage_percent} %>
<% else %>
 <%= render partial: 'fail', locals: {percent: @test_passage.passage_percent} %>
<% end %>
<br/>
<h3><%= link_to '<- To tests list', root_path %></h3>

app/views/results/show.html.erb
<h1>Passing the <%= @test_passage.test.title %> Test</h1>
<br/>
<p><%= questions_counter(@test_passage) %></p>
<br/>
<p>
  <%= content_tag :div, '', class: 'custom-progress-bar', data: {progress_bar: (@test_passage.current_question_number / @test_passage.test.questions.size.to_f) } do %>
    <div class="green-bar"></div>
  <% end %>
</p>
  <%= content_tag :div, '', class: 'timer' , data: { left_time: @test_passage.left_time } do %>
    <%= octicon 'clock' %>
  <% end %>
<br/>
<p>
  <b><%= @test_passage.current_question.body %></b>
</p>
<br/>
<%= form_with url: result_path(@test_passage), local: true, method: :put do |form|%>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answers_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
  <% end %>
  <br/>
  <p><%= link_to 'Gist question', gist_result_path(@test_passage), method: :post %></p>
  <br/>
  <p><%= form.submit 'Next', id: 'next-btn' %></p>
  <br/>
  <p class="red"><%= link_to 'Cancel', root_path %></p>
<% end %>