config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { registrations: :registrations, sessions: :sessions }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :results, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :badges, only: :index
  resources :own_badges, only: :index

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  belongs_to :test

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :find_question, only: %i[show edit update destroy]
  before_action :find_test, only: %i[new create]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_record_not_found

  def show; end

  def edit; end

  def new
    @question = @test.questions.new
  end

  def create
    @question = @test.questions.build(question_params)

    if @question.save
      redirect_to admin_test_path(@test)
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to admin_test_path(@question.test)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy!

    redirect_to admin_test_path(@question.test)
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_with_record_not_found
    render plain: 'Question not found'
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_form_header(question)
    if question.persisted?
      "Edit #{question.test.title} question"
    else
      "Create New #{question.test.title} question"
    end
  end
end

app/views/admin/questions/_form.html.erb
<h1> <%= question_form_header(@question) %> </h1>
<%= form_with model:[:admin, @test, @question], local: true, class: 'form' do |form| %>
  <%= render 'shared/errors', resource: @question %>

  <div class="text-area">
    <%= form.label :question%>
    <%= form.text_area :body, id: :body, size: "30x5" %>
    <%= form.submit %>
    <br/>
    <%= link_to '<- Back', admin_test_path(@question.test) %>
  </div>

<% end %>

app/views/admin/questions/_question.html.erb
<li>
  <p> <%= link_to question.body, admin_question_path(question) %></p>
  <div class="buttons-row">
  <p class="button-green"><%= link_to 'Edit', edit_admin_question_path(question) %></p>
  <p class="button-red"><%= link_to 'Delete',
              admin_question_path(question),
              method: :delete,
              data: { confirm: 'Are you sure to delete question?' } %>
  </p>
  </div>

</li>
<br/>

app/views/admin/questions/show.html.erb
<br/>
<p><%= @question.body %></p>
<br/>
<ol>
<%= render @question.answers %>
</ol>

<%= link_to '+ Add answer', new_admin_question_answer_path(@question) %>
<br/>
<%= link_to '<- Back', admin_test_path(@question.test) %>